language: python

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  global:
    - PYTHONPATH=$PYTHONPATH:$TRAVIS_BUILD_DIR:$TRAVIS_BUILD_DIR/source
    - CPLUS_INCLUDE_PATH=/usr/include/gdal
    - C_INCLUDE_PATH=/usr/include/gdal

cache:
  directories:
    - $GDALINST
    - ~/.cache/pip

addons:
  apt:
    packages:
      - gdal-bin
      - libproj-dev
      - libhdf5-serial-dev
      - libpng-dev
      - libgdal-dev
      - libatlas-dev
      - libatlas-base-dev
      - gfortran
      - netcdf-bin
      - libnetcdf-dev

before_install:
  - "pip install GDAL==1.10"
  - "pip install rasterio"
  - "pip install trefoil"
  - "pip install --upgrade setuptools"

install:
  - "python setup.py install"

script:
  - "py.test ."
